### ISSUE TITLE
Класс в StringToFilmConverter.java

### ISSUE THREAD

**Issue by anry-das** [Katiktus/Omdb#2]
Переименовать класс в StringToFilmConverter.java согласно конваенции

**Comment by Katiktus** [comment]
f12d177eef9e240089a520a6dbe41b7bbb23ae45

**Comment by Katiktus** [comment]
f46ed309954742f67f853dc87084434301dfd3f1

**Comment by Katiktus** [comment]
44ff0af3c9d7ab130b2f3014f15c060721264f6c
