### ISSUE TITLE
Замена для List<Film>

### ISSUE THREAD

**Issue by anry-das** [Katiktus/Omdb#6]
Можно List<Film> заменить на класс, икапсулирующий список.
Тогда результат ответа сервера с типом List<Film> будет выглядеть правилнее

**Comment by Katiktus** [comment]
1c36899d05055a20189c40fd5b2fec3f10ee165f

**Comment by Katiktus** [comment]
7a34e36812ed62a45fffb66c0dabaab82ce032a7
